### ISSUE TITLE
Players can't connect to server

### ISSUE THREAD

**Issue by Inxity** [VolmitSoftware/Rift#5]
When someone tries to connect to server, this appears on console and kicks the player.
I'm using Pufferfish 1.18.1
![image](https://user-images.githubusercontent.com/61350916/156213518-77035972-4799-4d2d-a990-c0338217aca3.png)

**Comment by NotAShelf** [comment]
does the user have op or `*`

**Comment by Inxity** [comment]
Yes, I had OP

**Comment by NotAShelf** [comment]
deop yourself or downgrade to 1.0.1, it's an ongoing issue with rift v2.0.0 (and I think the devs are aware)

**Comment by NextdoorPsycho** [comment]
We are aware, i just posted an update in General chat and there will be a jar update here
the code was correct, i mistakenly uploaded the wrong jar

**Comment by svdgoor** [comment]
@NextdoorPsycho this is still happening
plz fix

**Comment by svdgoor** [comment]
duplicate of #3
